# Generated by Django 5.1.7 on 2025-03-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0002_alter_specification_options_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Администратор'), ('technician', 'Техник'), ('user', 'Пользователь')], max_length=50, unique=True, verbose_name='Роль'),
        ),
    ]
